const express = require("express");
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { Readable } = require("stream");

const PORT = parseInt(process.env.PORT || "3000", 10);
const PLAYLIST_URL =
  process.env.PLAYLIST_URL || "https://iptv-org.github.io/iptv/countries/uk.m3u";
const REFRESH_HOURS = parseFloat(process.env.REFRESH_HOURS || "6");
// Signing secret for proxy URLs. Set PROXY_SECRET in production so stream
// URLs survive container restarts; falls back to a per-boot random key.
const SECRET = process.env.PROXY_SECRET || crypto.randomBytes(32).toString("hex");

// Some stream hosts reject requests without a browser-like UA
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

const app = express();
app.disable("x-powered-by");

let channels = [];
let lastRefresh = null;

// ---------------------------------------------------------------------------
// Channel filter — config/filter.json curates which channels are served.
// Re-read on every request (tiny file) so edits apply without a restart.
//   { "mode": "block", "channels": ["Aaj Tak"], "groups": ["Religious"] }
// mode "block" hides the listed names/groups; "allow" keeps ONLY matches.
// Missing or invalid file = no filtering. Matching is case-insensitive.
// ---------------------------------------------------------------------------

const FILTER_PATH = process.env.FILTER_PATH || path.join(__dirname, "config", "filter.json");

function loadFilter() {
  let raw;
  try {
    raw = JSON.parse(fs.readFileSync(FILTER_PATH, "utf8"));
  } catch {
    return null;
  }
  return {
    mode: raw.mode === "allow" ? "allow" : "block",
    channels: new Set((raw.channels || []).map((s) => String(s).toLowerCase())),
    groups: new Set((raw.groups || []).map((s) => String(s).toLowerCase())),
  };
}

function applyFilter(list) {
  const f = loadFilter();
  if (!f || (f.channels.size === 0 && f.groups.size === 0)) return list;
  const matches = (c) =>
    f.channels.has(c.name.toLowerCase()) ||
    c.groups.some((g) => f.groups.has(g.toLowerCase()));
  return f.mode === "allow" ? list.filter(matches) : list.filter((c) => !matches(c));
}

// ---------------------------------------------------------------------------
// Proxy URL signing — only URLs generated by this server can be proxied
// ---------------------------------------------------------------------------

function sign(url) {
  return crypto.createHmac("sha256", SECRET).update(url).digest("base64url").slice(0, 24);
}

function proxyUrl(url) {
  return `/stream?u=${Buffer.from(url).toString("base64url")}&s=${sign(url)}`;
}

function verifyProxyReq(req) {
  const { u, s } = req.query;
  if (typeof u !== "string" || typeof s !== "string") return null;
  let url;
  try {
    url = Buffer.from(u, "base64url").toString("utf8");
  } catch {
    return null;
  }
  const expected = sign(url);
  if (s.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(s), Buffer.from(expected))) {
    return null;
  }
  if (!/^https?:\/\//i.test(url)) return null;
  return url;
}

// ---------------------------------------------------------------------------
// Playlist fetch + parse
// ---------------------------------------------------------------------------

function parseAttrs(line) {
  const attrs = {};
  for (const m of line.matchAll(/([a-zA-Z0-9-]+)="([^"]*)"/g)) {
    attrs[m[1]] = m[2];
  }
  return attrs;
}

function parsePlaylist(text) {
  const lines = text.split(/\r?\n/);
  const out = [];
  let pending = null;

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith("#EXTINF")) {
      const attrs = parseAttrs(line);
      const name = line.slice(line.lastIndexOf(",") + 1).trim();
      pending = { attrs, name };
    } else if (!line.startsWith("#") && pending) {
      const { attrs, name } = pending;
      // Pull quality "(720p)" and status tags "[Not 24/7]" out of the name
      const quality = (name.match(/\((\d+p)\)/) || [])[1] || null;
      const tags = [...name.matchAll(/\[([^\]]+)\]/g)].map((m) => m[1]);
      const displayName = name.replace(/\s*\(\d+p\)/g, "").replace(/\s*\[[^\]]+\]/g, "").trim();
      out.push({
        id: crypto.createHash("sha1").update(line).digest("hex").slice(0, 12),
        name: displayName,
        quality,
        tags,
        logo: attrs["tvg-logo"] || null,
        // group-title can be compound, e.g. "Animation;Comedy;Kids"
        groups: (attrs["group-title"] || "Other")
          .split(";")
          .map((g) => g.trim())
          .filter(Boolean),
        url: line,
      });
      pending = null;
    }
  }
  return out;
}

let retryScheduled = false;

async function refreshChannels() {
  try {
    const resp = await fetch(PLAYLIST_URL, {
      headers: { "user-agent": UA },
      signal: AbortSignal.timeout(30000),
    });
    if (!resp.ok) throw new Error(`playlist fetch: HTTP ${resp.status}`);
    const parsed = parsePlaylist(await resp.text());
    if (parsed.length === 0) throw new Error("playlist parsed to 0 channels");
    channels = parsed;
    lastRefresh = new Date();
    console.log(`Playlist refreshed: ${channels.length} channels`);
  } catch (err) {
    console.error(`Playlist refresh failed: ${err.message}`);
    // Transient failures (e.g. network not ready at container start) —
    // retry soon rather than waiting for the next scheduled refresh
    if (!retryScheduled) {
      retryScheduled = true;
      setTimeout(() => {
        retryScheduled = false;
        refreshChannels();
      }, 60000);
    }
  }
}

// ---------------------------------------------------------------------------
// HLS proxy — pipes segments, rewrites playlists so all URIs route through us
// ---------------------------------------------------------------------------

function rewriteM3u8(text, baseUrl) {
  return text
    .split("\n")
    .map((line) => {
      const t = line.trim();
      if (!t) return line;
      if (t.startsWith("#")) {
        // Rewrite URI="..." in EXT-X-KEY, EXT-X-MEDIA, EXT-X-MAP, etc.
        return line.replace(/URI="([^"]+)"/g, (m, uri) => {
          try {
            return `URI="${proxyUrl(new URL(uri, baseUrl).href)}"`;
          } catch {
            return m;
          }
        });
      }
      try {
        return proxyUrl(new URL(t, baseUrl).href);
      } catch {
        return line;
      }
    })
    .join("\n");
}

app.get("/stream", async (req, res) => {
  const url = verifyProxyReq(req);
  if (!url) return res.status(403).send("Invalid stream URL");

  let upstream;
  try {
    upstream = await fetch(url, {
      headers: { "user-agent": UA },
      redirect: "follow",
      signal: AbortSignal.timeout(20000),
    });
  } catch (err) {
    return res.status(502).send("Upstream fetch failed");
  }
  if (!upstream.ok) {
    return res.status(502).send(`Upstream HTTP ${upstream.status}`);
  }

  const finalUrl = upstream.url || url;
  const ctype = (upstream.headers.get("content-type") || "").toLowerCase();
  const looksLikePlaylist =
    ctype.includes("mpegurl") ||
    ctype.includes("m3u") ||
    new URL(finalUrl).pathname.toLowerCase().endsWith(".m3u8");

  if (looksLikePlaylist) {
    try {
      const text = await upstream.text();
      res.set("content-type", "application/vnd.apple.mpegurl");
      res.set("cache-control", "no-store");
      return res.send(rewriteM3u8(text, finalUrl));
    } catch {
      return res.status(502).send("Failed to read upstream playlist");
    }
  }

  res.set("content-type", ctype || "video/mp2t");
  res.set("cache-control", "no-store");
  const body = Readable.fromWeb(upstream.body);
  body.on("error", () => res.destroy());
  res.on("close", () => body.destroy());
  body.pipe(res);
});

// ---------------------------------------------------------------------------
// API + static
// ---------------------------------------------------------------------------

app.get("/api/channels", (req, res) => {
  res.json({
    lastRefresh,
    channels: applyFilter(channels).map((c) => ({
      id: c.id,
      name: c.name,
      quality: c.quality,
      tags: c.tags,
      logo: c.logo,
      groups: c.groups,
      src: proxyUrl(c.url),
    })),
  });
});

app.get("/healthz", (req, res) => {
  res.json({
    ok: true,
    channels: channels.length,
    visible: applyFilter(channels).length,
    lastRefresh,
  });
});

app.use(express.static(path.join(__dirname, "public")));

refreshChannels();
setInterval(refreshChannels, REFRESH_HOURS * 60 * 60 * 1000);

app.listen(PORT, () => console.log(`IPTV server listening on :${PORT}`));
