const express = require("express");
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { Readable } = require("stream");
const epg = require("./epg");

const PORT = parseInt(process.env.PORT || "3000", 10);
const PLAYLIST_URL =
  process.env.PLAYLIST_URL || "https://iptv-org.github.io/iptv/countries/uk.m3u";
const REFRESH_HOURS = parseFloat(process.env.REFRESH_HOURS || "6");
// Signing secret for proxy URLs. Set PROXY_SECRET in production so stream
// URLs survive container restarts; falls back to a per-boot random key.
const SECRET = process.env.PROXY_SECRET || crypto.randomBytes(32).toString("hex");

// Some stream hosts reject requests without a browser-like UA
const UA =
  "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36";

const app = express();
app.disable("x-powered-by");
// Behind Traefik — real client IP arrives in X-Forwarded-For
app.set("trust proxy", true);

let channels = [];
let lastRefresh = null;

// ---------------------------------------------------------------------------
// Channel filter — config/filter.json curates which channels are served.
// Re-read on every request (tiny file) so edits apply without a restart.
//   { "mode": "block", "channels": ["Aaj Tak"], "groups": ["Religious"] }
// mode "block" hides the listed names/groups; "allow" keeps ONLY matches.
// Missing or invalid file = no filtering. Matching is case-insensitive.
// ---------------------------------------------------------------------------

const FILTER_PATH = process.env.FILTER_PATH || path.join(__dirname, "config", "filter.json");

function loadFilter() {
  let raw;
  try {
    raw = JSON.parse(fs.readFileSync(FILTER_PATH, "utf8"));
  } catch {
    return null;
  }
  return {
    mode: raw.mode === "allow" ? "allow" : "block",
    channels: new Set((raw.channels || []).map((s) => String(s).toLowerCase())),
    groups: new Set((raw.groups || []).map((s) => String(s).toLowerCase())),
  };
}

function applyFilter(list) {
  const f = loadFilter();
  if (!f || (f.channels.size === 0 && f.groups.size === 0)) return list;
  const matches = (c) =>
    f.channels.has(c.name.toLowerCase()) ||
    c.groups.some((g) => f.groups.has(g.toLowerCase()));
  return f.mode === "allow" ? list.filter(matches) : list.filter((c) => !matches(c));
}

// ---------------------------------------------------------------------------
// Proxy URL signing — only URLs generated by this server can be proxied
// ---------------------------------------------------------------------------

function sign(url) {
  return crypto.createHmac("sha256", SECRET).update(url).digest("base64url").slice(0, 24);
}

function proxyUrl(url, channelId) {
  const c = channelId ? `&c=${channelId}` : "";
  return `/stream?u=${Buffer.from(url).toString("base64url")}&s=${sign(url)}${c}`;
}

function verifyProxyReq(req) {
  const { u, s } = req.query;
  if (typeof u !== "string" || typeof s !== "string") return null;
  let url;
  try {
    url = Buffer.from(u, "base64url").toString("utf8");
  } catch {
    return null;
  }
  const expected = sign(url);
  if (s.length !== expected.length || !crypto.timingSafeEqual(Buffer.from(s), Buffer.from(expected))) {
    return null;
  }
  if (!/^https?:\/\//i.test(url)) return null;
  return url;
}

// ---------------------------------------------------------------------------
// Playlist fetch + parse
// ---------------------------------------------------------------------------

function parseAttrs(line) {
  const attrs = {};
  for (const m of line.matchAll(/([a-zA-Z0-9-]+)="([^"]*)"/g)) {
    attrs[m[1]] = m[2];
  }
  return attrs;
}

function parsePlaylist(text) {
  const lines = text.split(/\r?\n/);
  const out = [];
  let pending = null;

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) continue;
    if (line.startsWith("#EXTINF")) {
      const attrs = parseAttrs(line);
      const name = line.slice(line.lastIndexOf(",") + 1).trim();
      pending = { attrs, name };
    } else if (!line.startsWith("#") && pending) {
      const { attrs, name } = pending;
      // Pull quality "(720p)" and status tags "[Not 24/7]" out of the name
      const quality = (name.match(/\((\d+p)\)/) || [])[1] || null;
      const tags = [...name.matchAll(/\[([^\]]+)\]/g)].map((m) => m[1]);
      const displayName = name.replace(/\s*\(\d+p\)/g, "").replace(/\s*\[[^\]]+\]/g, "").trim();
      out.push({
        id: crypto.createHash("sha1").update(line).digest("hex").slice(0, 12),
        tvgId: attrs["tvg-id"] || null,
        name: displayName,
        quality,
        tags,
        logo: attrs["tvg-logo"] || null,
        // group-title can be compound, e.g. "Animation;Comedy;Kids"
        groups: (attrs["group-title"] || "Other")
          .split(";")
          .map((g) => g.trim())
          .filter(Boolean),
        url: line,
      });
      pending = null;
    }
  }
  return out;
}

let retryScheduled = false;

async function refreshChannels() {
  try {
    const resp = await fetch(PLAYLIST_URL, {
      headers: { "user-agent": UA },
      signal: AbortSignal.timeout(30000),
    });
    if (!resp.ok) throw new Error(`playlist fetch: HTTP ${resp.status}`);
    const parsed = parsePlaylist(await resp.text());
    if (parsed.length === 0) throw new Error("playlist parsed to 0 channels");
    channels = parsed;
    lastRefresh = new Date();
    console.log(`Playlist refreshed: ${channels.length} channels`);
    epg.rebuildMapping(channels);
  } catch (err) {
    console.error(`Playlist refresh failed: ${err.message}`);
    // Transient failures (e.g. network not ready at container start) —
    // retry soon rather than waiting for the next scheduled refresh
    if (!retryScheduled) {
      retryScheduled = true;
      setTimeout(() => {
        retryScheduled = false;
        refreshChannels();
      }, 60000);
    }
  }
}

// ---------------------------------------------------------------------------
// Viewer session tracking — every playback request hits /stream, so segment
// fetches double as a heartbeat. A session is one IP watching one channel;
// it ends after SESSION_GAP_MS without a request.
// ---------------------------------------------------------------------------

const dns = require("dns");

const SESSION_GAP_MS = 2 * 60 * 1000;
const sessions = new Map(); // "ip|channelId" -> session
const history = []; // ended sessions, newest first
const rdnsCache = new Map(); // ip -> { host, at }

function resolveHost(ip) {
  const hit = rdnsCache.get(ip);
  if (hit && Date.now() - hit.at < 3600e3) return;
  rdnsCache.set(ip, { host: null, at: Date.now() });
  dns.promises
    .reverse(ip)
    .then((names) => rdnsCache.set(ip, { host: names[0] || null, at: Date.now() }))
    .catch(() => {});
}

function endSession(key) {
  const s = sessions.get(key);
  if (!s) return;
  sessions.delete(key);
  history.unshift({ ...s, endedAt: s.lastSeen });
  if (history.length > 200) history.length = 200;
}

function trackView(req, channelId) {
  const ip = req.ip || req.socket.remoteAddress || "unknown";
  const key = `${ip}|${channelId}`;
  const now = Date.now();
  let s = sessions.get(key);
  if (s && now - s.lastSeen > SESSION_GAP_MS) {
    endSession(key);
    s = null;
  }
  if (!s) {
    s = {
      ip,
      channelId,
      firstSeen: now,
      lastSeen: now,
      bytes: 0,
      ua: req.headers["user-agent"] || "",
    };
    sessions.set(key, s);
    resolveHost(ip);
  }
  s.lastSeen = now;
  return s;
}

// Sweep idle sessions into history
setInterval(() => {
  const now = Date.now();
  for (const [key, s] of sessions) {
    if (now - s.lastSeen > SESSION_GAP_MS) endSession(key);
  }
}, 30000);

// ---------------------------------------------------------------------------
// HLS proxy — pipes segments, rewrites playlists so all URIs route through us
// ---------------------------------------------------------------------------

function rewriteM3u8(text, baseUrl, channelId) {
  return text
    .split("\n")
    .map((line) => {
      const t = line.trim();
      if (!t) return line;
      if (t.startsWith("#")) {
        // Rewrite URI="..." in EXT-X-KEY, EXT-X-MEDIA, EXT-X-MAP, etc.
        return line.replace(/URI="([^"]+)"/g, (m, uri) => {
          try {
            return `URI="${proxyUrl(new URL(uri, baseUrl).href, channelId)}"`;
          } catch {
            return m;
          }
        });
      }
      try {
        return proxyUrl(new URL(t, baseUrl).href, channelId);
      } catch {
        return line;
      }
    })
    .join("\n");
}

app.get("/stream", async (req, res) => {
  const url = verifyProxyReq(req);
  if (!url) return res.status(403).send("Invalid stream URL");

  const channelId = typeof req.query.c === "string" ? req.query.c.slice(0, 16) : null;
  const sess = channelId ? trackView(req, channelId) : null;

  let upstream;
  try {
    upstream = await fetch(url, {
      headers: { "user-agent": UA },
      redirect: "follow",
      signal: AbortSignal.timeout(20000),
    });
  } catch (err) {
    return res.status(502).send("Upstream fetch failed");
  }
  if (!upstream.ok) {
    return res.status(502).send(`Upstream HTTP ${upstream.status}`);
  }

  const finalUrl = upstream.url || url;
  const ctype = (upstream.headers.get("content-type") || "").toLowerCase();
  const looksLikePlaylist =
    ctype.includes("mpegurl") ||
    ctype.includes("m3u") ||
    new URL(finalUrl).pathname.toLowerCase().endsWith(".m3u8");

  if (looksLikePlaylist) {
    try {
      const text = await upstream.text();
      res.set("content-type", "application/vnd.apple.mpegurl");
      res.set("cache-control", "no-store");
      if (sess) sess.bytes += text.length;
      return res.send(rewriteM3u8(text, finalUrl, channelId));
    } catch {
      return res.status(502).send("Failed to read upstream playlist");
    }
  }

  res.set("content-type", ctype || "video/mp2t");
  res.set("cache-control", "no-store");
  const body = Readable.fromWeb(upstream.body);
  if (sess) body.on("data", (d) => (sess.bytes += d.length));
  body.on("error", () => res.destroy());
  res.on("close", () => body.destroy());
  body.pipe(res);
});

// ---------------------------------------------------------------------------
// API + static
// ---------------------------------------------------------------------------

app.get("/api/channels", (req, res) => {
  res.json({
    lastRefresh,
    channels: applyFilter(channels).map((c) => ({
      id: c.id,
      name: c.name,
      quality: c.quality,
      tags: c.tags,
      logo: c.logo,
      groups: c.groups,
      src: proxyUrl(c.url, c.id),
    })),
  });
});

// Now & next for filtered channels only — payload stays small
app.get("/api/epg", (req, res) => {
  const visible = new Set(applyFilter(channels).map((c) => c.id));
  const all = epg.getNowNext();
  const out = {};
  for (const [id, v] of Object.entries(all)) if (visible.has(id)) out[id] = v;
  res.json({ epg: out });
});

app.get("/api/epg/status", (req, res) => {
  res.json(epg.status());
});

app.get("/api/admin/sessions", (req, res) => {
  const nameOf = (id) => channels.find((c) => c.id === id)?.name || id;
  const shape = (s) => ({
    ip: s.ip,
    host: rdnsCache.get(s.ip)?.host || null,
    channel: nameOf(s.channelId),
    firstSeen: s.firstSeen,
    lastSeen: s.lastSeen,
    endedAt: s.endedAt || null,
    bytes: s.bytes,
    ua: s.ua,
  });
  res.json({
    now: Date.now(),
    active: [...sessions.values()].sort((a, b) => a.firstSeen - b.firstSeen).map(shape),
    recent: history.slice(0, 50).map(shape),
  });
});

app.get("/healthz", (req, res) => {
  res.json({
    ok: true,
    channels: channels.length,
    visible: applyFilter(channels).length,
    lastRefresh,
  });
});

app.use(express.static(path.join(__dirname, "public")));

refreshChannels();
setInterval(refreshChannels, REFRESH_HOURS * 60 * 60 * 1000);

let epgRetryScheduled = false;
async function refreshEpgSafe() {
  try {
    await epg.refreshEpg(() => channels);
  } catch (err) {
    console.error(`EPG refresh failed: ${err.message}`);
    if (!epgRetryScheduled) {
      epgRetryScheduled = true;
      setTimeout(() => {
        epgRetryScheduled = false;
        refreshEpgSafe();
      }, 10 * 60 * 1000);
    }
  }
}
refreshEpgSafe();
setInterval(refreshEpgSafe, 12 * 60 * 60 * 1000);

app.listen(PORT, () => console.log(`IPTV server listening on :${PORT}`));
